### ISSUE TITLE
Error by using client and listen

### ISSUE THREAD

**Issue by NsSumse** [senecajs/seneca#146] opened 2015-08-04 09:15 UTC
I have wrote some code:

server.js:

    var seneca = require('seneca')()
    seneca
      .add( 
        'role:math,cmd:sum', 
        function( msg, respond ) {
          var sum = msg.left + msg.right
          respond( null, { answer: sum } )
        }).listen()

client.js:

    var seneca = require('seneca')({ timeout:99999})
                 .client({host: "localhost"})
    			 .on('ready', start);

    function start() {
        for (var i = 0; i < 10000; i++) {
    	seneca.act( 'role:math,cmd:sum,left:1.5,right:2.5', 
            console.log // prints { answer: 4, info: '1.5+2.5' }
          )
        }
    }

I'm starting the server.
After that i start the client tow times, that they run paralell.
I get this Error:

2015-08-04T08:59:56.136Z yqha2ygqggac/1438678729175/19360/- WARN        plugin  transport       ACT icuqh4u2cejp/mr0qd0nhudal   hook:client,role:transport,type:web     client  no_message_id   {type:web,port:10101,host:localhost,path:/act,protocol:http,timeout:99444,msgprefix:seneca_,callmax:111111,msgi {kind:res,res:null,error:Error: connect ECONNREFUSED,time:{client_recv:1438678796136}}

**Comment by rjrodger** [comment] 2015-08-18 21:31
.client and .listen should always be the same, so try .listen( {host:"localhost" })

**Comment by NsSumse** [comment] 2015-08-20 12:50
Thank you for the answer.

But i get the same error like before.
If i run only one client i don't get this error.
This error will be thrown if i run the clients paralell.

At first I get this error:

    2015-08-20T12:33:19.436Z brnbyjpd8yzx/1440073966473/4600/- WARN plugin  transport       ACT    g0k3znqbxbk7/jssu5eg1huzp       hook:client,role:transport,type:
    web     client  no_message_id   {type:web,port:10101,host:localhost,path:/act,protocol:http,timeout:9999444,msgprefix:seneca_,callmax:111111,ms {kind:res,res:null,error:Error: connect ECONNREFUSED,time:{client_recv:1440073999436}}

Then I got the right answer:

    null { answer: 4 }
    null { answer: 4 }
    null { answer: 4 }
    null { answer: 4 }
    null { answer: 4 }

At the end of the excetution i get this error:

    2015-08-20T12:43:59.621Z aveg6mh5bnsi/1440074277730/7156/- ERROR        act     remote$         OUT     -       358549  {role:math,cmd:sum,left:1.5,right:2.5}
    ENTRY   CLIENT  -       seneca: Action  failed: [TIMEOUT].      act_execute     {id:trx97bx1nh4p/yg9sl3o2zmg7,gate:false,ungate:false,desc:,plugin:{name:remote$
    ,tag:null},time:{start:14400742 Error: [TIMEOUT]
        at null._onTimeout (C:\xxx\seneca\node_modules\seneca\node_modules\gate-executor\gate-executor.js:95:21)
        at Timer.listOnTimeout (timers.js:119:15)
    { [Error: seneca: Action  failed: [TIMEOUT].]
      timeout: true,
      eraro: true,
      orig:
       { [Error: gate-executor: [TIMEOUT]]
         timeout: true,
         eraro: true,
         orig: { [Error: [TIMEOUT]] timeout: true },
         code: 'action-timeout',
         'gate-executor': true,
         package: 'gate-executor',
         msg: 'gate-executor: [TIMEOUT]',
         details:
          { id: 'trx97bx1nh4p/yg9sl3o2zmg7',
            gate: false,
            ungate: false,
            desc: '',
            cb: [Function],
            plugin: [Object],
            fn: [Function],
            time: [Object],
            'orig$': [Object],
            'message$': '[TIMEOUT]' },
         callpoint: 'at null._onTimeout (C:\\xxx\\seneca\\node_modules\\seneca\\node_modules\\gate-executor\\gate-executor.js:95:21)' },
      code: 'act_execute',
      'gate-executor': true,
      package: 'seneca',
      msg: 'seneca: Action  failed: [TIMEOUT].',
      details:
       { id: 'trx97bx1nh4p/yg9sl3o2zmg7',
         gate: false,
         ungate: false,
         desc: '',
         cb: [Function],
         plugin: { name: 'remote$', tag: undefined },
         fn: [Function],
         time: { start: 1440074286967, end: 1440074639621 },
         'orig$': { [Error: [TIMEOUT]] timeout: true },
         'message$': '[TIMEOUT]',
         message: '[TIMEOUT]',
         pattern: '',
         instance: 'Seneca/0.6.4/aveg6mh5bnsi/1440074277730/7156/-' },
      callpoint: 'at null._onTimeout (C:\\xxx\\seneca\\node_modules\\seneca\\node_modules\\gate-executor\\gate-executor.js:95:21)',
      seneca: true }

**Comment by rjrodger** [comment] 2015-08-27 21:23
ok, will try to reproduce

**Comment by rjrodger** [comment] 2015-08-27 22:07
So the problem is this line: `for (var i = 0; i < 10000; i++) {`
This is generating 10000 *concurrent* requests - which is a nice load test :)

On my machine (MacBook Pro), this actually works error free if you don't do a `console.log`
If I push it to 100000 then it breaks with timeouts as per your comments - as messages just cannot be processed quickly enough.

What sort of load do you expect?

**Comment by rjrodger** [comment] 2015-09-14 12:01
@geek need to consider windows machines for transport test harness too

**Comment by geek** [comment] 2015-09-15 00:39
@NsSumse are you trying to determine load/processing time for a request?  https://github.com/isaacs/node-bench may be useful to try.

I can reproduce a timeout on windows, but it only is an issue with load and nothing specific to windows... if I reduce the iterations to 1000 the timeout goes away.

**Comment by mcdonnelldean** [comment] 2015-10-22 10:30
@NsSumse I've also ran on a Windows VM. Same as results as @geek. 

On having to specify 'localhost' over Seneca managing this for you... This is currently something I am testing out. We think we have a solution so I'm just assessing the impact. 

I'm going to go ahead and close this as a load limit query but if you need anymore info or discussion go ahead and open it back up. We're always happy to help out :D

**Closed by mcdonnelldean** 2015-10-22 10:30 UTC
Labels: need-info

**Comment by dsaikiran** [comment] 2016-03-31 07:37
Hi, 
I need to catch that exception and handle it, how to capture that timeout / connection refused exceptions?

**Comment by geek** [comment] 2016-03-31 15:51
@dsaikiran seneca exposes the error event.  I am marking this as a request, we can also expose a timeout event, which I am open to accepting a PR on

**Comment by AkashSouravNayak** [comment] 2016-07-12 10:33
how we can know how many concurrent call can be done in seneca?

**Comment by mcdonnelldean** [comment] 2016-07-12 10:37
@AkashSouravNayak Please open a fresh issue for non related questions. Cheers.
