### ISSUE TITLE
Memory usage keeps growing when using remote transport

### ISSUE THREAD

**Issue by salaerts** [senecajs/seneca#408] opened 2016-04-27 14:36 UTC
We are currently building a distributed application that uses the built-in http transport.
To simplify the scenario: we have van API (service A) that takes requests from clients and a background service that stores/fetches data (service B).

When we put high load on this system the memory usage grows fast and the claimed memory is never released. Both service A & B have this problem, although service A (the client of B) has much higher memory growth when compared to service B.
(Sending 15.000 requests to service A from 4 separate processes makes the memory usage go from 80MB to 500+MB in a couple of minutes.)

When stripping down the code we managed to pin-point the issue to seneca.act calls.
So we started on a repro project to simplify this.

First we made a small app that just used seneca.act to call a local plugin.
```javascript
var seneca = require('seneca')();

seneca.ready(function(err) {
  seneca.add({ role: 'test', cmd: 'run' }, function(msg, respond) {
    console.log('received call, replying to msg # ' + msg.count);
    respond(null, { reply: 'OK ' + msg.count });
  });

  executeAct(1);
});

function executeAct(count) {
  if (count > 50000) {
    return;
  }

  var pattern = { role: 'test', cmd: 'run', count: count };

  seneca.act(pattern, function(err, result) {
    if (err) {
      console.error(err);
      process.exit();
      return;
    }

    console.log(result);
    count = count + 1;
    executeAct(count);
  });
}
```

We can see some minor memory usages spikes while running but the memory seems to be properly managed. (Starts at about 80Mb, spikes to 101Mb but drops down to 80-90Mb again while running.)

Next we made a small example that does the exact same thing but using the http transport.
Client code:
```javascript
var seneca = require('seneca')();

seneca.ready(function(err) {
  seneca.client({
    type: 'web',
    host: 'localhost',
    port: 4455,
    pin: 'role:test'
  });

  executeAct(1);
});

function executeAct(count) {
  if (count > 10000) {
    return;
  }

  var pattern = { role: 'test', cmd: 'run', count: count };

  seneca.act(pattern, function(err, result) {
    if (err) {
      console.error(err);
      process.exit();
      return;
    }

    console.log(result);
    count = count + 1;
    executeAct(count);
  });
}
```

Server code:
```javascript
var seneca = require('seneca')();

seneca.ready(function(err) {
  seneca.add({ role: 'test', cmd: 'run' }, function(msg, respond) {
    console.log('received call, replying to msg # ' + msg.count);
    respond(null, { reply: 'OK ' + msg.count });
  });

  seneca.listen({
    type: 'web',
    host: 'localhost',
    port: 4455,
    pin: 'role:test'
  });
});
```

When running this sample the memory usage keeps rising and never drops.
We also tried changing the transport to seneca-amqp-transport with the exact same results.

We tried this with:
NodeJS 4.4
Seneca 1.2.0, 1.3.0, 1.4.0 and 2.0.1

We tried all of these seneca versions and the problem seems to exist everywhere.
Which begs the question: are doing something wrong here?

**Comment by mcollina** [comment] 2016-04-27 14:39
Just to confirm, is your process crashing for out of memory? Can you try running this long enough to get to this point?

Memory spikes under high traffic are _normal_ in node apps under high load, as V8 runs the collector when it has time, i.e. when the load is lower. There techniques to mitigate this, but we need to ensure that we are in this case rather than a memory leak.

**Comment by mcdonnelldean** [comment] 2016-04-27 15:21
@salaerts Could you move this to seneca-transport? Simply follow this link and paste it? That way we can focus on this as a transport problem (which it may be). The first step is to respond to @mcollina From there we will write an integration test based on the code above to see if we can reliably reproduce. If we can we should be able to figure out pretty quickly were the issue is or if it is just 'hot path' issues.

Once you move it let me know and I will close this.

**Comment by salaerts** [comment] 2016-04-27 15:30
Just moved it. (#95)

**Comment by mcdonnelldean** [comment] 2016-04-27 15:31
Awesome stuff, we are doing some transport stuff over the next 10 days so I'll add in this test once I am at it.

**Closed by mcdonnelldean** 2016-04-27 15:31 UTC
Labels: investigate, need-info
