### ISSUE TITLE
How can reduce start time 

### ISSUE THREAD

**Issue by mjafarpour** [senecajs/seneca#615] opened 2017-03-25 15:41 UTC
Hi,

I recently use Seneca in my new application, when i test our code for performance and run-time speed, i see the start time of my code when use Seneca increased and when without it in my code run very quickly.
Seneca run-time is a fix time, when i include Seneca plugin that increase 1 second and when add seneca.use() to my code it's  add another 1 second to the run time of code. 
The test was in my laptop not in a production use.

How can i reduce the the start time for Seneca?

**Comment by rjrodger** [comment] 2017-04-11 16:05
@mjafarpour You should see <200ms. How are you measuring the start time? A small test case with code would be very helpful.

**Comment by rjrodger** [comment] 2017-04-11 16:08
Do you see the same delay using: https://github.com/senecajs/seneca/blob/master/test/stubs/launch.js

**Comment by rjrodger** [comment] 2017-04-11 16:11
I also added some test code in my dev repo: https://github.com/rjrodger/seneca/commit/7688c3199542e3d295bdfa5936961dbacd034805
This prints out the start time

**Comment by rjrodger** [comment] 2018-08-07 16:13
closing as can't reproduce

**Closed by rjrodger** 2018-08-07 16:13 UTC
Labels: investigate, more info needed
