### ISSUE TITLE
idgen is not a function

### ISSUE THREAD

**Issue by geek** [senecajs/seneca#370] opened 2016-03-14 16:05 UTC
Copied from: https://github.com/senecajs/seneca/issues/26#issuecomment-195335123

https://github.com/senecajs/senecajs.org/blob/master/src/pages/tutorials/seneca-with-promises.md#advanced-example

and got:

```
2016-03-11T11:42:40.685Z b5tr3kr5vzx8/1457696560620/1544/- INFO hello   Seneca/1.3.0/b5tr3kr5vzx8/1457696560620/1544/-  
[TypeError: Object #<Object> has no method 'idgen']
```

**Comment by cjnqt** [comment] 2016-03-20 22:00
+1 
I've seen this bug a couple of times when working with a promises.

**Comment by japel** [comment] 2016-04-08 09:12
Any news on this? Anyone else experiencing a similar behavior?

**Comment by Takeno** [comment] 2016-05-04 13:21
That error is caused by the wrong `Promise.promisify`'s parameters.

Docs: http://bluebirdjs.com/docs/api/promise.promisify.html

As you can see in this commit, the promisify function is now accepting an object as second parameter.
https://github.com/petkaantonov/bluebird/commit/2a28d466439586d5ae755b0f538a5cc6974395ba#diff-1f0dd9d666794c01ded659349cb2512eR271


In order to fix the promification, you have to wrap the context in object.

Eg: 
```
var act = Promise.promisify(seneca.act, {context: seneca});
```

**Comment by Takeno** [comment] 2016-05-04 13:27
I just found the same issue in seneca.org repo: https://github.com/senecajs/senecajs.org/issues/207

**Comment by mcdonnelldean** [comment] 2016-05-04 14:12
As @Takeno says, it is coved in the docs, 

http://senecajs.org/tutorials/seneca-with-promises.html#basic-example

Unfortunately it is not very visible and looks more like a throw away comment. I will make this more explicit in the documentation so that people know it is the correct fix.

Closing as the actual issue is to use context correctly.

**Closed by mcdonnelldean** 2016-05-04 14:12 UTC

**Comment by doliver3** [comment] 2016-08-29 06:05
This link no longer works: http://senecajs.org/tutorials/seneca-with-promises.html#basic-example
Is there an updated link that describes how to use seneca with promises?

**Comment by mcdonnelldean** [comment] 2016-08-29 09:10
@doliver3 I have corrected the link. It should be live in the next hour. There was a missing call to seneca-entity in the tutorial.
