### ISSUE TITLE
Entity resolver in Seneca-basic autoloading

### ISSUE THREAD

**Issue by jreeter** [senecajs/seneca#213] opened 2015-11-03 16:50 UTC
When executing execute_reset from Seneca-user I am getting:  'The property \'user\', with current value: \'4fi1e0\', must be a object (parent: top level).',

Executing code: execute_reset({token: resetToken, password: userPassword}

Per @rjrodger he thinks this is an issue with the entity resolver in Seneca-basic which auto loads entries from their ids.

**Comment by paolochiodi** [comment] 2015-11-10 14:50
I guess this is a duplicate of https://github.com/rjrodger/seneca-user/issues/7 that was fixed by https://github.com/rjrodger/seneca-user/pull/9, but I'm afraid this never got published to npm.

@rjrodger can we publish a new release of seneca-user?

**Comment by rjrodger** [comment] 2015-11-16 16:12
yes! /cc @mcdonnelldean @mirceaalexandru time to publish your work on seneca-user :)

**Comment by mcdonnelldean** [comment] 2016-04-27 21:52
Done

**Closed by mcdonnelldean** 2016-04-27 21:52 UTC
