### ISSUE TITLE
Lab not able to support our testing scenario

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#423] opened 2016-05-13 13:02 UTC
Folks,

We need to make a decision on how to progress forward here. Right now we support,

- 0.10
- 0.12
- 4
- 5

We are looking to bring in support for Node V6 but can't because the version of Lab that supports V6 only includes backwards support to V4.

Granted we could probably drop 0.10 soon enough but there are a lot of folks still on 0.12. I'm not at all comfortable dropping support because the testing rig won't support it, especially if the code base itself is compatible (as is the case here).

@rjrodger @geek Thoughts on how to proceed here? We are of the impression that Seneca may work as is or with minor modifications for V6, having the test tool stop us supporting a version is not ideal.

//cc @mihaidma

**Comment by geek** [comment] 2016-05-13 15:36
If you need support for node 0.12 and 0.10, you can use lab v6.x.x and disable the leak checks: `--leaks`

However, I recommend cutting support for node 0.12 and requiring node >= 4.0.0 going forward for seneca 3.0.0.

**Comment by mcdonnelldean** [comment] 2016-05-13 15:42
@geek 3.0.0 is too early for us to drop 0.12. The plan is to do it in the November release. Will the above give us support for Node v6? When disabling `--leaks` what is the side effect from that? Is it disabling leak checking generally?

**Comment by geek** [comment] 2016-05-13 16:10
@mcdonnelldean it disables checking for global leaks.

**Comment by mcollina** [comment] 2016-05-13 16:22
@geek can you please explain what is the issue? Maybe there is a simple workaround that can keep support for the leak check in node v0.12.

**Comment by geek** [comment] 2016-05-13 23:18
node 6 deprecated accessing `root`... I have this fixed in the latest lab.  Previously, it was accessing global.root, which is where the warning appears.  Another option is also to disable deprecation warnings in node.

**Comment by mcollina** [comment] 2016-05-14 07:37
@geek would it be possible to support the old mode (for 0.12) and the new mode (6+) with a version test (or feature check)? Something like https://github.com/calvinmetcalf/process-nextick-args/blob/master/index.js#L3-L9 (used in readable-stream).

**Comment by mihaidma** [comment] 2016-05-14 08:46
I verified Lab 6 with Node 6 and `--leaks`, it works: https://github.com/hapijs/lab/issues/581#issuecomment-219079708
This solves our problem.

I'll add through scripting `--leaks` on tests running on Node 6 and that will fix our issue until we drop 0.10 and 0.12 support.

**Comment by mihaidma** [comment] 2016-05-16 13:31
I think the issue is solved. I posted details on devlog: https://github.com/nearform/devlog/issues/12

**Comment by AdrianRossouw** [comment] 2016-05-17 11:31
i think this has been resolved now. 

closing.

**Closed by AdrianRossouw** 2016-05-17 11:31 UTC
Labels: investigate
